"""
Please follow below rules while designing automation script as
• Accept input through command line or through file.
• Display any message in log file instead of console.
• For separate task define separate function.
• For robustness handle every expected exception.
• Perform validations before taking any action.
• Create user defined modules to store the functionality.

4. Design automation script which accept directory name and mail id from user and create log file in that directory which contains information of running processes as Its name, PID, Username. After creating log file send that log file to the specified mail. 
Usage : ProcInfoLog.py Demo Marvellousinfosystem@gmail.com 
Demo is name of Directory. 
marvellousinfosystem@gmail.com is the mail id.
"""

import psutil
import sys
import os
import time
import smtplib
from email.message import EmailMessage

def ProcessScan():
    listprocess = []

    for proc in psutil.process_iter():
        info = proc.as_dict(attrs=["pid","name","username"])

        listprocess.append(info)

    return listprocess

def Marvellous_send(sender, app_password, receiver, subject, body, filename):

    msg = EmailMessage()

    msg["From"] = sender
    msg["To"] = receiver
    msg["Subject"] = subject

    # High priority headers
    msg["X-Priority"] = "1"
    msg["Priority"] = "urgent"
    msg["Importance"] = "high"

    msg.set_content(body)

    fobj = open(filename,"rb")
    FileData = fobj.read()
    FileName = os.path.basename(filename)
    fobj.close()

    msg.add_attachment(FileData,
                       maintype="application",
                       subtype="octet-stream",
                       filename=FileName)

    smtp = smtplib.SMTP_SSL("smtp.gmail.com",465)

    smtp.login(sender,app_password)

    smtp.send_message(msg)

    smtp.quit()

    print("Mail sent successfully")

# Process Information
def ProcessInfo(FolderName, ReceiverMail):
    Border = "-" * 50

    Ret = False

    Ret = os.path.exists(FolderName)

    if(Ret == True):
        Ret = os.path.isdir(FolderName)
        if(Ret == False):
            print("Unable to proceed as directory name is existing nut its not a directory")
            return
    else:
        os.mkdir(FolderName)
        print("Directory for the logfile gets creted successfully")

    timestamp = time.strftime("%Y-%m-%d_%H-%M-%S")

    FileName = os.path.join(FolderName, "ProcessInfo_%s.log" %timestamp)

    fObj = open(FileName, "w")

    print(f"Log file get successfully created with name {FileName}")

    fObj.write(Border + "\n")
    fObj.write("---- Marvellous Process Information System ----\n")
    fObj.write("Log file gets created at : " + timestamp + "\n")
    fObj.write(Border + "\n\n")

    fObj.write("---------------- System Report ----------------\n")

    # Process Log
    Data = ProcessScan()

    for info in Data:
        fObj.write("Name : %s\n" %info.get("name"))
        fObj.write("PID : %s\n" %info.get("pid"))
        fObj.write("User Name : %s\n" %info.get("username"))
        fObj.write(Border + "\n")

    # Log file footer
    fObj.write(Border + "\n")
    fObj.write("--------------- End of log file ---------------\n")
    fObj.write(Border + "\n")

    fObj.close()

    # Email

    SenderMail = "sahilpatil9763@gmail.com"
    AppPassword = "yjoz ilxo rzkw bfvi"

    Subject = f"Platform Surveillance Log - {time.strftime('%d-%m-%Y %I:%M:%S %p')}"

    Body = """
Hello,

Please find the attached Process Information Log generated by my Python Automation Script.

The log file contains details of the currently running processes, including their Process ID (PID), Process Name, and Username.

Date: {}

This is an automatically generated email. Please do not reply to this message.

Regards,

Sahil Patil (PID - 249)
Python Automation Project
Inspired by Marvellous Infosystems
""".format(time.strftime("%d-%m-%Y %I:%M:%S %p"))

    Marvellous_send(
        SenderMail,
        AppPassword,
        ReceiverMail,
        Subject,
        Body,
        FileName
    )

# Main Function
def main():

    Border = "-" * 50

    print(Border)
    print("----- Marvellous Platform Surveillance System -----")
    print(Border)

    if len(sys.argv) != 3:
        print("Invalid number of arguments")
        print(f"Usage : python {sys.argv[0]} Folder_Name")
        return

    if sys.argv[1] == "--h" or sys.argv[1] == "--H":
        print("This automation script displays information of running processes")
        return

    if sys.argv[1] == "--u" or sys.argv[1] == "--U":
        print(f"Usage : python {sys.argv[0]} Folder_Name Receiver_Email")
        return

    FolderName = sys.argv[1]
    ReceiverMail = sys.argv[2]

    ProcessInfo(FolderName, ReceiverMail)

    print(Border)
    print("--- Thank you for using our Automation System ---")
    print(Border)

if __name__ == "__main__":
    main()